<a href="https://colab.research.google.com/github/RUDRAKSHALAKESANNA/-Technical-Assignment-PRM-/blob/main/Copy_of_Dataanalyst_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 4

In [ ]:
order_reports=pd.read_excel("/content/Company X - Order Report.xlsx")
order_reports

,ExternOrderNo,SKU,Order Qty,Payment Mode,Item Price(Per Qty.)
0,2001827036,8904223818706,1,COD,233
1,2001827036,8904223819093,1,COD,233
2,2001827036,8904223819109,1,COD,233
3,2001827036,8904223818430,1,COD,470
4,2001827036,8904223819277,1,COD,233
...,...,...,...,...,...
395,2001806229,8904223818942,1,COD,286
396,2001806229,8904223818850,1,COD,563
397,2001806226,8904223818850,2,COD,1125
398,2001806210,8904223816214,1,COD,402
399,2001806210,8904223818874,1,COD,922

In [ ]:
SKU_master=pd.read_excel("/content/Company X - SKU Master.xlsx")
SKU_master

              SKU  Weight (g)
0   8904223815682         210
1   8904223815859         165
2   8904223815866         113
3   8904223815873          65
4   8904223816214         120
..            ...         ...
61  8904223819505         210
62  8904223819499         210
63  8904223819512         210
64  8904223819543         300
65     SACHETS001          10

[66 rows x 2 columns]

In [ ]:
pincode_mapping=pd.read_excel("/content/Company X - Pincode Zones.xlsx")
pincode_mapping

     Warehouse Pincode  Customer Pincode Zone
0               121003            507101    d
1               121003            486886    d
2               121003            532484    d
3               121003            143001    b
4               121003            515591    d
..                 ...               ...  ...
119             121003            325207    b
120             121003            303702    b
121             121003            313301    b
122             121003            173212    e
123             121003            302020    b

[124 rows x 3 columns]

In [ ]:
common_column="SKU"
merged_df = pd.merge(SKU_master, order_reports, on=common_column)

merged_df

,SKU,Weight (g),ExternOrderNo,Order Qty,Payment Mode,Item Price(Per Qty.)
0,8904223815682,210,2001808801,1,Prepaid,965
1,8904223815859,165,2001820978,1,Prepaid,951
2,8904223815859,165,2001811363,1,Prepaid,951
3,8904223815859,165,2001811363,1,Prepaid,951
4,8904223815859,165,2001808801,1,Prepaid,951
...,...,...,...,...,...,...
396,8904223819512,210,2001806733,1,Prepaid,534
397,8904223819543,300,2001811306,1,Prepaid,653
398,SACHETS001,10,2001827036,1,COD,350
399,SACHETS001,10,2001825261,1,Prepaid,350
400,SACHETS001,10,2001819252,1,Prepaid,350

In [ ]:
merged_df.rename(columns={'ExternOrderNo': 'Order ID'}, inplace=True)
merged_df

,SKU,Weight (g),Order ID,Order Qty,Payment Mode,Item Price(Per Qty.)
0,8904223815682,210,2001808801,1,Prepaid,965
1,8904223815859,165,2001820978,1,Prepaid,951
2,8904223815859,165,2001811363,1,Prepaid,951
3,8904223815859,165,2001811363,1,Prepaid,951
4,8904223815859,165,2001808801,1,Prepaid,951
...,...,...,...,...,...,...
396,8904223819512,210,2001806733,1,Prepaid,534
397,8904223819543,300,2001811306,1,Prepaid,653
398,SACHETS001,10,2001827036,1,COD,350
399,SACHETS001,10,2001825261,1,Prepaid,350
400,SACHETS001,10,2001819252,1,Prepaid,350

In [ ]:
invoice=pd.read_excel("/content/Courier Company - Invoice.xlsx")
invoice

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.)
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0
1,1091117222194,2001806273,1.00,121003,486886,d,Forward charges,101.2
2,1091117222931,2001806408,2.50,121003,532484,d,Forward charges,224.6
3,1091117223244,2001806458,1.00,121003,143001,b,Forward charges,61.3
4,1091117229345,2001807012,0.15,121003,515591,d,Forward charges,45.4
...,...,...,...,...,...,...,...,...
119,1091118551656,2001812941,0.73,121003,325207,d,Forward charges,95.2
120,1091117614452,2001809383,0.50,121003,303702,d,Forward and RTO charges,86.7
121,1091120922803,2001820978,0.50,121003,313301,d,Forward charges,45.4
122,1091121844806,2001811475,0.50,121003,173212,b,Forward charges,47.0
123,1091121846136,2001811305,0.50,121003,302020,d,Forward charges,65.4

In [ ]:
common_column="Order ID"
merged_df1 = pd.merge(invoice, merged_df, on=common_column)

merged_df1

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.),SKU,Weight (g),Order Qty,Payment Mode,Item Price(Per Qty.)
0,1091117222124,2001806232,1.3,121003,507101,d,Forward charges,140.0,8904223818645,137,6,COD,1673
1,1091117222124,2001806232,1.3,121003,507101,d,Forward charges,140.0,8904223819147,240,2,COD,466
2,1091117222194,2001806273,1.0,121003,486886,d,Forward charges,101.2,8904223818706,127,1,COD,233
3,1091117222194,2001806273,1.0,121003,486886,d,Forward charges,101.2,8904223818850,240,1,COD,563
4,1091117222194,2001806273,1.0,121003,486886,d,Forward charges,101.2,8904223818942,133,1,COD,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,1091121844806,2001811475,0.5,121003,173212,b,Forward charges,47.0,8904223819499,210,1,COD,960
397,1091121846136,2001811305,0.5,121003,302020,d,Forward charges,65.4,8904223816214,120,1,COD,402
398,1091121846136,2001811305,0.5,121003,302020,d,Forward charges,65.4,8904223819505,210,1,COD,350
399,1091121846136,2001811305,0.5,121003,302020,d,Forward charges,65.4,8904223819499,210,1,COD,960
400,1091121846136,2001811305,0.5,121003,302020,d,Forward charges,65.4,8904223819512,210,1,COD,534

In [ ]:
common_column="Warehouse Pincode"
merged_df2 = pd.merge(pincode_mapping, merged_df1, on=common_column)

merged_df2

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),SKU,Weight (g),Order Qty,Payment Mode,Item Price(Per Qty.)
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,8904223818645,137,6,COD,1673
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,8904223819147,240,2,COD,466
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818706,127,1,COD,233
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818850,240,1,COD,563
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818942,133,1,COD,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,302020,b,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,8904223819499,210,1,COD,960
49720,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223816214,120,1,COD,402
49721,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819505,210,1,COD,350
49722,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819499,210,1,COD,960
49723,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819512,210,1,COD,534

In [ ]:
merged_df2['Total Weight'] = merged_df2['Order Qty'] * merged_df2['Weight (g)']
merged_df2

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),SKU,Weight (g),Order Qty,Payment Mode,Item Price(Per Qty.),Total Weight
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,8904223818645,137,6,COD,1673,822
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,8904223819147,240,2,COD,466,480
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818706,127,1,COD,233,127
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818850,240,1,COD,563,240
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818942,133,1,COD,286,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,302020,b,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,8904223819499,210,1,COD,960,210
49720,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223816214,120,1,COD,402,120
49721,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819505,210,1,COD,350,210
49722,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819499,210,1,COD,960,210
49723,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819512,210,1,COD,534,210

In [ ]:
Rates=pd.read_excel("/content/Courier Company - Rates.xlsx")
Rates

,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge
0,A,0.25,29.5,23.6,13.6,23.6
1,B,0.50,33.0,28.3,20.5,28.3
2,C,0.75,40.1,38.9,31.9,38.9
3,D,1.25,45.4,44.8,41.3,44.8
4,E,1.50,56.6,55.5,50.7,55.5

In [ ]:
def get_delivery_zone(row):
    if row['Zone_x'] =="a":
        return 'A'
    elif row['Zone_x']=="b":
        return 'B'
    elif row['Zone_x']=="c":
        return 'C'
    elif row['Zone_x']=="d":
        return 'D'
    elif row['Zone_x']=="e":
        return 'E'

merged_df2['Delivery Zone'] = merged_df2.apply(get_delivery_zone, axis=1)
merged_df2

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),SKU,Weight (g),Order Qty,Payment Mode,Item Price(Per Qty.),Total Weight,Delivery Zone
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,8904223818645,137,6,COD,1673,822,D
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,8904223819147,240,2,COD,466,480,D
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818706,127,1,COD,233,127,D
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818850,240,1,COD,563,240,D
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818942,133,1,COD,286,133,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,302020,b,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,8904223819499,210,1,COD,960,210,B
49720,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223816214,120,1,COD,402,120,B
49721,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819505,210,1,COD,350,210,B
49722,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819499,210,1,COD,960,210,B
49723,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819512,210,1,COD,534,210,B

In [ ]:
merged_df2.rename(columns={'Delivery Zone': 'Zone'}, inplace=True)
merged_df2

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),SKU,Weight (g),Order Qty,Payment Mode,Item Price(Per Qty.),Total Weight,Zone
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,8904223818645,137,6,COD,1673,822,D
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,8904223819147,240,2,COD,466,480,D
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818706,127,1,COD,233,127,D
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818850,240,1,COD,563,240,D
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,8904223818942,133,1,COD,286,133,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,302020,b,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,8904223819499,210,1,COD,960,210,B
49720,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223816214,120,1,COD,402,120,B
49721,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819505,210,1,COD,350,210,B
49722,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819499,210,1,COD,960,210,B
49723,121003,302020,b,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,8904223819512,210,1,COD,534,210,B

In [ ]:
common_column="Zone"
merged_df3 = pd.merge(merged_df2, Rates, on=common_column)

merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,Order Qty,Payment Mode,Item Price(Per Qty.),Total Weight,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,6,COD,1673,822,D,1.25,45.4,44.8,41.3,44.8
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,2,COD,466,480,D,1.25,45.4,44.8,41.3,44.8
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,1,COD,233,127,D,1.25,45.4,44.8,41.3,44.8
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,1,COD,563,240,D,1.25,45.4,44.8,41.3,44.8
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,1,COD,286,133,D,1.25,45.4,44.8,41.3,44.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,1,COD,960,210,E,1.50,56.6,55.5,50.7,55.5
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,1,COD,402,120,E,1.50,56.6,55.5,50.7,55.5
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,1,COD,350,210,E,1.50,56.6,55.5,50.7,55.5
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,1,COD,960,210,E,1.50,56.6,55.5,50.7,55.5
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,1,COD,534,210,E,1.50,56.6,55.5,50.7,55.5

In [ ]:
def calculate_cod_charge(row):
    if row['Payment Mode'] == 'Prepaid':
        return 0
    else:
        if row['Item Price(Per Qty.)'] <= 300:
            return 15
        else:
            return 0.05 * row['Item Price(Per Qty.)']


merged_df3['COD Charge'] = merged_df3.apply(calculate_cod_charge, axis=1)
merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,Payment Mode,Item Price(Per Qty.),Total Weight,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,COD Charge
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,COD,1673,822,D,1.25,45.4,44.8,41.3,44.8,83.65
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,COD,466,480,D,1.25,45.4,44.8,41.3,44.8,23.30
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,COD,233,127,D,1.25,45.4,44.8,41.3,44.8,15.00
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,COD,563,240,D,1.25,45.4,44.8,41.3,44.8,28.15
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,COD,286,133,D,1.25,45.4,44.8,41.3,44.8,15.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,COD,960,210,E,1.50,56.6,55.5,50.7,55.5,48.00
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,COD,402,120,E,1.50,56.6,55.5,50.7,55.5,20.10
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,COD,350,210,E,1.50,56.6,55.5,50.7,55.5,17.50
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,COD,960,210,E,1.50,56.6,55.5,50.7,55.5,48.00
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,COD,534,210,E,1.50,56.6,55.5,50.7,55.5,26.70

In [ ]:
merged_df3["courier forwad charges"]=merged_df3["Item Price(Per Qty.)"]*merged_df3["Weight Slabs"]+merged_df3["Forward Fixed Charge"]
merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,Item Price(Per Qty.),Total Weight,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,COD Charge,courier forwad charges
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,1673,822,D,1.25,45.4,44.8,41.3,44.8,83.65,2136.65
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,466,480,D,1.25,45.4,44.8,41.3,44.8,23.30,627.90
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,233,127,D,1.25,45.4,44.8,41.3,44.8,15.00,336.65
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,563,240,D,1.25,45.4,44.8,41.3,44.8,28.15,749.15
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,286,133,D,1.25,45.4,44.8,41.3,44.8,15.00,402.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,960,210,E,1.50,56.6,55.5,50.7,55.5,48.00,1496.60
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,402,120,E,1.50,56.6,55.5,50.7,55.5,20.10,659.60
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,350,210,E,1.50,56.6,55.5,50.7,55.5,17.50,581.60
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,960,210,E,1.50,56.6,55.5,50.7,55.5,48.00,1496.60
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,534,210,E,1.50,56.6,55.5,50.7,55.5,26.70,857.60

In [ ]:
merged_df3["courier rto cahrges"]=merged_df3["Item Price(Per Qty.)"]*merged_df3["Weight Slabs"]+merged_df3["RTO Fixed Charge"]
merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,Total Weight,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,COD Charge,courier forwad charges,courier rto cahrges
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,822,D,1.25,45.4,44.8,41.3,44.8,83.65,2136.65,2132.55
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,480,D,1.25,45.4,44.8,41.3,44.8,23.30,627.90,623.80
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,127,D,1.25,45.4,44.8,41.3,44.8,15.00,336.65,332.55
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,240,D,1.25,45.4,44.8,41.3,44.8,28.15,749.15,745.05
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,133,D,1.25,45.4,44.8,41.3,44.8,15.00,402.90,398.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,210,E,1.50,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,120,E,1.50,56.6,55.5,50.7,55.5,20.10,659.60,653.70
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,210,E,1.50,56.6,55.5,50.7,55.5,17.50,581.60,575.70
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,210,E,1.50,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,210,E,1.50,56.6,55.5,50.7,55.5,26.70,857.60,851.70

In [ ]:
merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,Total Weight,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,COD Charge,courier forwad charges,courier rto cahrges
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,822,D,1.25,45.4,44.8,41.3,44.8,83.65,2136.65,2132.55
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,480,D,1.25,45.4,44.8,41.3,44.8,23.30,627.90,623.80
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,127,D,1.25,45.4,44.8,41.3,44.8,15.00,336.65,332.55
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,240,D,1.25,45.4,44.8,41.3,44.8,28.15,749.15,745.05
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,133,D,1.25,45.4,44.8,41.3,44.8,15.00,402.90,398.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,210,E,1.50,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,120,E,1.50,56.6,55.5,50.7,55.5,20.10,659.60,653.70
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,210,E,1.50,56.6,55.5,50.7,55.5,17.50,581.60,575.70
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,210,E,1.50,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,210,E,1.50,56.6,55.5,50.7,55.5,26.70,857.60,851.70

In [ ]:
merged_df3[" courier total charge"]=merged_df3["COD Charge"]+merged_df3["courier forwad charges"]+merged_df3["courier rto cahrges"]
merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,COD Charge,courier forwad charges,courier rto cahrges,courier total charge
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,D,1.25,45.4,44.8,41.3,44.8,83.65,2136.65,2132.55,4352.85
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,D,1.25,45.4,44.8,41.3,44.8,23.30,627.90,623.80,1275.00
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,D,1.25,45.4,44.8,41.3,44.8,15.00,336.65,332.55,684.20
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,D,1.25,45.4,44.8,41.3,44.8,28.15,749.15,745.05,1522.35
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,D,1.25,45.4,44.8,41.3,44.8,15.00,402.90,398.80,816.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,E,1.50,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70,3035.30
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,E,1.50,56.6,55.5,50.7,55.5,20.10,659.60,653.70,1333.40
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,E,1.50,56.6,55.5,50.7,55.5,17.50,581.60,575.70,1174.80
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,E,1.50,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70,3035.30
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,E,1.50,56.6,55.5,50.7,55.5,26.70,857.60,851.70,1736.00

In [ ]:
merged_df3["X forwad charges"]=merged_df3["Item Price(Per Qty.)"]*merged_df3["Weight Slabs"]+merged_df3["Forward Additional Weight Slab Charge"]
merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,COD Charge,courier forwad charges,courier rto cahrges,courier total charge,X forwad charges
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,1.25,45.4,44.8,41.3,44.8,83.65,2136.65,2132.55,4352.85,2136.05
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,1.25,45.4,44.8,41.3,44.8,23.30,627.90,623.80,1275.00,627.30
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,1.25,45.4,44.8,41.3,44.8,15.00,336.65,332.55,684.20,336.05
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,1.25,45.4,44.8,41.3,44.8,28.15,749.15,745.05,1522.35,748.55
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,1.25,45.4,44.8,41.3,44.8,15.00,402.90,398.80,816.70,402.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,1.50,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70,3035.30,1495.50
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,1.50,56.6,55.5,50.7,55.5,20.10,659.60,653.70,1333.40,658.50
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,1.50,56.6,55.5,50.7,55.5,17.50,581.60,575.70,1174.80,580.50
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,1.50,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70,3035.30,1495.50
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,1.50,56.6,55.5,50.7,55.5,26.70,857.60,851.70,1736.00,856.50

In [ ]:
merged_df3["X rto cahrges"]=merged_df3["Item Price(Per Qty.)"]*merged_df3["Weight Slabs"]+merged_df3["RTO Additional Weight Slab Charge"]
merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,COD Charge,courier forwad charges,courier rto cahrges,courier total charge,X forwad charges,X rto cahrges
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,45.4,44.8,41.3,44.8,83.65,2136.65,2132.55,4352.85,2136.05,2136.05
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,45.4,44.8,41.3,44.8,23.30,627.90,623.80,1275.00,627.30,627.30
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,45.4,44.8,41.3,44.8,15.00,336.65,332.55,684.20,336.05,336.05
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,45.4,44.8,41.3,44.8,28.15,749.15,745.05,1522.35,748.55,748.55
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,45.4,44.8,41.3,44.8,15.00,402.90,398.80,816.70,402.30,402.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70,3035.30,1495.50,1495.50
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,56.6,55.5,50.7,55.5,20.10,659.60,653.70,1333.40,658.50,658.50
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,56.6,55.5,50.7,55.5,17.50,581.60,575.70,1174.80,580.50,580.50
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,56.6,55.5,50.7,55.5,48.00,1496.60,1490.70,3035.30,1495.50,1495.50
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,56.6,55.5,50.7,55.5,26.70,857.60,851.70,1736.00,856.50,856.50

In [ ]:
merged_df3[" X total charge"]=merged_df3["COD Charge"]+merged_df3["X forwad charges"]+merged_df3["X rto cahrges"]
merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,COD Charge,courier forwad charges,courier rto cahrges,courier total charge,X forwad charges,X rto cahrges,X total charge
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,44.8,41.3,44.8,83.65,2136.65,2132.55,4352.85,2136.05,2136.05,4355.75
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,44.8,41.3,44.8,23.30,627.90,623.80,1275.00,627.30,627.30,1277.90
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,44.8,41.3,44.8,15.00,336.65,332.55,684.20,336.05,336.05,687.10
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,44.8,41.3,44.8,28.15,749.15,745.05,1522.35,748.55,748.55,1525.25
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,44.8,41.3,44.8,15.00,402.90,398.80,816.70,402.30,402.30,819.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,55.5,50.7,55.5,48.00,1496.60,1490.70,3035.30,1495.50,1495.50,3039.00
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,55.5,50.7,55.5,20.10,659.60,653.70,1333.40,658.50,658.50,1337.10
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,55.5,50.7,55.5,17.50,581.60,575.70,1174.80,580.50,580.50,1178.50
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,55.5,50.7,55.5,48.00,1496.60,1490.70,3035.30,1495.50,1495.50,3039.00
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,55.5,50.7,55.5,26.70,857.60,851.70,1736.00,856.50,856.50,1739.70

In [ ]:
merged_df3.to_csv('merged_df3.csv')

In [ ]:
merged_df3["difference"]=merged_df3[" X total charge"] - merged_df3[" courier total charge"]

In [ ]:
merged_df3

,Warehouse Pincode,Customer Pincode_x,Zone_x,AWB Code,Order ID,Charged Weight,Customer Pincode_y,Zone_y,Type of Shipment,Billing Amount (Rs.),...,RTO Fixed Charge,RTO Additional Weight Slab Charge,COD Charge,courier forwad charges,courier rto cahrges,courier total charge,X forwad charges,X rto cahrges,X total charge,difference
0,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,41.3,44.8,83.65,2136.65,2132.55,4352.85,2136.05,2136.05,4355.75,2.9
1,121003,507101,d,1091117222124,2001806232,1.3,507101,d,Forward charges,140.0,...,41.3,44.8,23.30,627.90,623.80,1275.00,627.30,627.30,1277.90,2.9
2,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,41.3,44.8,15.00,336.65,332.55,684.20,336.05,336.05,687.10,2.9
3,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,41.3,44.8,28.15,749.15,745.05,1522.35,748.55,748.55,1525.25,2.9
4,121003,507101,d,1091117222194,2001806273,1.0,486886,d,Forward charges,101.2,...,41.3,44.8,15.00,402.90,398.80,816.70,402.30,402.30,819.60,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49719,121003,173212,e,1091121844806,2001811475,0.5,173212,b,Forward charges,47.0,...,50.7,55.5,48.00,1496.60,1490.70,3035.30,1495.50,1495.50,3039.00,3.7
49720,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,50.7,55.5,20.10,659.60,653.70,1333.40,658.50,658.50,1337.10,3.7
49721,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,50.7,55.5,17.50,581.60,575.70,1174.80,580.50,580.50,1178.50,3.7
49722,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,50.7,55.5,48.00,1496.60,1490.70,3035.30,1495.50,1495.50,3039.00,3.7
49723,121003,173212,e,1091121846136,2001811305,0.5,302020,d,Forward charges,65.4,...,50.7,55.5,26.70,857.60,851.70,1736.00,856.50,856.50,1739.70,3.7

In [ ]:
merged_df3.to_csv('merged_df3.csv')